spring:
  application:
    name: spring-ai-mcp-server

  datasource:
    url: ${JDBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: true
        schema-name: public
        table-name: rag_document_store

    mcp:
      server:
        protocol: STREAMABLE

server:
  port: ${MCP_SERVER_CONTAINER:8081}

app:
  upload-dir: ${APP_UPLOAD_DIR:/app/uploads}

logging:
  level:
    "[org.springframework.ai]": DEBUG

