spring:
  application:
    name: mcp-client

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 2000

    vectorstore:
      pgvector:
        initialize-schema: true
        schema-name: public
        table-name: chat_memory_store
    mcp:
      client:
        streamable-http:
          connections:
            server1:
              url: http://localhost:8081

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

app:
  upload-dir: ../uploads

logging:
  level:
    "[org.springframework.ai]": DEBUG

